openapi: 3.0.0

info:
  title: "{{title}}"
  version: "{{version}}"
  description: Authentication API Document

servers:
  - url: http://localhost:8000/api/v1   #v1 is base URL

paths:
  /auth/login:
    post:
      summary: login user
      operationId: authapi.auth.login
      requestBody:
        description: user info to login
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /:  #path
    get:
      summary: index page
      operationId: authapi.hello.index
      responses:
        '200':
          description: index
          content:
            'text/plain':
              schema:
                type: string
  /hello: #path
    get:
      summary: hello world
      operationId: authapi.hello.hello
      responses:
        '200':
          description: say hello
          content:
            'application/json':
              schema:
                type: string
      security:
        - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: authapi.auth.decode_token

  schemas:
    LoginUser:
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: username
        password:
          type: string
          example: password