openapi: 3.0.0

info:
  title: {{title}}
  version: {{version}}
  description: Authentication API Document

servers:
  - url: http://localhost:8000/api/v1   #v1 is base URL

paths:
  /:  #path
    get:
      summary: index page
      operationId: authapi.hello.index
      responses:
        '200':
          description: index
          content:
            'text/plain':
              schema:
                type: string
#  /hello: #path
#    get:
#      summary: hello world
#      operationId: authapi.hello.hello
#      responses:
#        '200':
#          description: say hello
#          content:
#            'application/json':
#              schema:
#                type: string
#      security:
#        - jwt: ['secret']